resource_types:    
- name: azure-blob
  type: docker-image
  source:
    repository: cfcloudops/azure-blobstore-concourse-resource
- name: email
  type: docker-image
  source:
    repository: pcfseceng/email-resource
    tag: latest

resources:
- name: azure-blobstore
  type: azure-blob
  source:
    storage_account_name: ((storage_account_name))
    storage_access_key: ((storage_account_key))
    container: ((container))
    regexp: report/bcr-report-([0-9\.]+).txt
    environment: AzureCloud

- name: this-repo
  type: git
  source:
    uri: ((this_git_repo_uri))
    branch: ((this_git_repo_branch))

- name: bcr-plugin
  type: github-release
  source:
    owner: avasseur-pivotal
    repository: cf_get_events
    access_token: ((github_access_token))

- name: container-image
  type: docker-image
  source:
    repository: ((container_image_repository))

- name: on-monday
  type: time
  source:
    days: [Monday, Tuesday, Wednesday, Thursday, Friday]
    interval: 24h

- name: send-an-email
  type: email
  source:
    smtp:
      host: ((smtp-server))
      port: ((smtp-port))
      username: ((smtp-username))
      password: ((smtp-password))
    from: ((email-from))
    to: ((email-to))

jobs:
- name: generate-bcr-report
  plan:
    - aggregate:
      - get: on-monday
        trigger: true
      - get: container-image
      - get: bcr-plugin
      - get: this-repo
    - task: run-bcr
      image: container-image
      file: this-repo/tasks/run-bcr/task.yml
      params:
        CF_API_URL: ((cf_api_url))
        CF_API_LOGIN: ((cf_api.username))
        CF_API_PASSWORD: ((cf_api.password))
    - put: send-an-email
      params:
        subject_text: ((email-subject-text))
        body_text: ((email-body-text))
        attachment_globs: ["report/*.txt"]
    - put: azure-blobstore
      params: { file: report/bcr-report-*.txt }

